%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 1280
image_height: 720
distortion_parameters:
   k1: 0.0
   k2: 0.0
   p1: 0.0
   p2: 0.0
projection_parameters:
   fx: 798.86273193
   fy: 799.02679443
   cx: 649.10675049
   cy: 345.32125854
resolution_multiplier: 0.5