%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 1280
image_height: 720
distortion_parameters:
   k1: 0.0
   k2: 0.0
   p1: 0.0
   p2: 0.0
projection_parameters:
   fx: 797.52770996
   fy: 797.22631836
   cx: 615.95568848
   cy: 343.50363159
resolution_multiplier: 0.5